### ISSUE TITLE
gorm2添加数据无法获得已添加的id

### ISSUE THREAD

**Issue by code-gopher** [sliveryou/grom#2]
错误的
type TestModel struct {
        ID           int    `json:"id" gorm:"primaryKey;column:id;type:int(11) auto_increment"`
        Name         string `json:"name" gorm:"column:name;type:char(50)"`
}

正确的
type TestModel struct {
        ID           int    `json:"id" gorm:"primaryKey;column:id;type:int(11);autoIncrement"`
        Name         string `json:"name" gorm:"column:name;type:char(50)"`
}

**Comment by sliveryou** [comment]
fix in 5309c2834d458cc27572ccad67ae97217323cb12
